theme: jekyll-theme-chirpy

lang: en

timezone: Europe/London

title: Suraj Remanan

tagline: DevOps Engineer, Self-Hosting Enthusiast, Human.

description: >-
  I' m Suraj, a Senior DevOps Engineer, specializing in Kubernetes, Docker, Terraform, Configuration Management, CI/CD, Automation and Observability in both conventional and cloud-native environments. 
  I've worked with a diverse set of global clients, including international banks, telecommunication services, retail businesses and financial services.

url: "https://surajremanan.com"

github:
  username: c0depool

social:
  name: Suraj Remanan
  email: hello@surajremanan.com
  links:
    - https://www.linkedin.com/in/suraj-remanan
    - https://github.com/c0depool
    
webmaster_verifications:
  google: Wc42KYxjRIVyttJfZJDgp-TmHFfCds6ts3uxXuA_Ug0

analytics:
  goatcounter:
    id: surajremanan

pageviews:
  provider: goatcounter


theme_mode: # [light|dark]

img_cdn:

avatar: "assets/img/profile.webp"

social_preview_image: # string, local or CORS resources

toc: true

comments:
  provider: giscus
  giscus:
    repo: c0depool/c0depool-blog
    repo_id: R_kgDOLGPppQ
    category: General
    category_id: DIC_kwDOLGPppc4Cd2mX
    mapping: title
    input_position: # optional, default to 'bottom'
    lang: # optional, default to the value of `site.lang`
    reactions_enabled: 1

# Self-hosted static assets, optional › https://github.com/cotes2020/chirpy-static-assets
assets:
  self_host:
    enabled: # boolean, keep empty means false
    # specify the Jekyll environment, empty means both
    # only works if `assets.self_host.enabled` is 'true'
    env: # [development|production]

pwa:
  enabled: true # the option for PWA feature

paginate: 10

# The base URL of your site
baseurl: ""

# ------------ The following options are not recommended to be modified ------------------

kramdown:
  footnote_backlink: "&#8617;&#xfe0e;"
  syntax_highlighter: rouge
  syntax_highlighter_opts: # Rouge Options › https://github.com/jneen/rouge#full-options
    css_class: highlight
    # default_lang: console
    span:
      line_numbers: false
    block:
      line_numbers: true
      start_line: 1

collections:
  tabs:
    output: true
    sort_by: order

defaults:
  - scope:
      path: "" # An empty string here means all files in the project
      type: posts
    values:
      layout: post
      comments: true # Enable comments in posts.
      toc: true # Display TOC column in posts.
      # DO NOT modify the following parameter unless you are confident enough
      # to update the code of all other post links in this project.
      permalink: /posts/:title/
  - scope:
      path: _drafts
    values:
      comments: false
  - scope:
      path: ""
      type: tabs # see `site.collections`
    values:
      layout: page
      permalink: /:title/
  - scope:
      path: assets/img/favicons
    values:
      swcache: true

sass:
  style: compressed

compress_html:
  clippings: all
  comments: all
  endings: all
  profile: false
  blanklines: false
  ignore:
    envs: [development]

exclude:
  - "*.gem"
  - "*.gemspec"
  - docs
  - tools
  - README.md
  - LICENSE
  - purgecss.js
  - "*.config.js"
  - "package*.json"

jekyll-archives:
  enabled: [categories, tags]
  layouts:
    category: category
    tag: tag
  permalinks:
    tag: /tags/:name/
    category: /categories/:name/

plugins:
  - jekyll-target-blank
  - jekyll-redirect-from