# frozen_string_literal: true

source "https://rubygems.org"

gem "jekyll-theme-chirpy", "7.4.1"

gem "html-proofer", "5.2.0", group: :test

# Make links open in new tab
gem "jekyll-target-blank", "2.0.2"

# Redirect to and from
gem "jekyll-redirect-from", "0.16.0"