name: Bump version

on:
  pull_request:
    paths:
      - app/**
      - Dockerfile
      - nginx.conf
    types:
      - closed
    branches:
      - main

jobs:
  build:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-24.04
    steps:
    - uses: actions/checkout@v4.3.0
      with:
        ref: ${{ github.event.pull_request.merge_commit_sha }}
        fetch-depth: '0'

    - name: Bump version and push tag
      uses: anothrNick/github-tag-action@1.75.0
      env:
        GITHUB_TOKEN: ${{ secrets.PAT }}
        WITH_V: true
        DEFAULT_BUMP: patch
